apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "podo.fullname" . }}
  labels:
    {{- include "podo.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "podo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "podo.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "podo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: UPSTREAM_INGRESS_CLASS_NAME
              value: {{ .Values.podo.upstreamIngressClassName | quote}}
            - name: PODO_INGRESS_CLASS_NAME
              value: {{ .Values.podo.podoIngressClassName | quote}}
            - name: PODO_SERVICE_NAME
              value: {{ include "podo.fullname" . }}
            - name: STARTUP_RETRY_COUNT
              value: {{ .Values.podo.retryCount | quote }}
            - name: INACTIVE_DEPLOYMENT_SHUTDOWN_TIME_H
              value: {{ .Values.podo.depolymentShutdownTime | quote }}
            - name: PODO_INGRESS_URL
              value: http{{ if .Values.ingress.tls }}s{{ end }}://{{ .Values.ingress.host }}{{ .Values.ingress.path }}podo/
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
